ext_localconf.php

Fix extension name in plugin registration

---

Documentation/Index.rst
Documentation/Introduction/Index.rst
Documentation/Settings.cfg

List all examples in the documentation and link to where they are explained in the documentation.
Squashed the commit manually.

[Feature] List examples in Extension documentation

---

.editorconfig
Classes/DataProcessing/CustomCategoryProcessor.php
Configuration/TCA/Overrides/tt_content.php
Configuration/TCA/tx_examples_haiku.php
Configuration/TSconfig/Page/ContentElementWizard.typoscript
Configuration/TypoScript/setup.typoscript
Documentation/Introduction/Index.rst
Documentation/Settings.cfg
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Templates/ContentElements/DataProcCsv.html
Resources/Private/Templates/ContentElements/DataProcCustom.html
Resources/Private/Templates/ContentElements/DataProcDb.html
Resources/Private/Templates/ContentElements/DataProcFiles.html
Resources/Private/Templates/ContentElements/DataProcGallery.html
Resources/Private/Templates/ContentElements/DataProcLangMenu.html
Resources/Private/Templates/ContentElements/DataProcMenu.html
Resources/Private/Templates/ContentElements/DataProcSite.html
Resources/Private/Templates/ContentElements/DataProcSplit.html
Resources/Private/Templates/NewContentElement.html
composer.json
ext_tables.php
ext_tables.sql

Data Processor examples that can be used in TSref and TYPO3 explained to make screenshots and have working examples

[Feature] DataProcessor examples

---

Documentation/Settings.cfg
README.rst

See TYPO3-Documentation/TYPO3CMS-Code-Examples#31

[TASK] Rename repository to TYPO3-Documentation/t3docs-examples

---

.github/workflows/publish.yml
composer.json

[TASK] Publish TER release by GitHub Action v9

---

.github/workflows/publish.yml
composer.json

[TASK] Publish TER release by GitHub Action v10

---

Classes/Userfuncs/CustomMenu.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TypoScript/HmenuSpecial/setup.typoscript
Initialisation/data.xml

refs https://github.com/TYPO3-Documentation/t3docs-screenshots/issues/151

[FEATURE] Move HMENU special userfunc example from TSREF

---

Initialisation/Site/introduction/config.yaml
Initialisation/data.xml.files/5ce68d800123c1203b1d21d6b862aebf3f260117

- add a site configuration
- rearange templates
refs https://github.com/TYPO3-Documentation/t3docs-screenshots/issues/164

[FEATURE] enable automatic screenshots of the frontend

---

Classes/LinkHandler/GitHubLinkHandler.php
Resources/Private/Templates/LinkBrowser/GitHub.html

Resolves: #57
Releases: master

[BUGFIX] Make GitHub link handler TYPO3 11.4 compatible

---

Classes/Userfuncs/CustomMenu.php

See TYPO3-Documentation/T3DocTeam#165 for details.

[TASK] Unify top-level domain of dummy urls

---

Classes/Xclass/NewRecordController.php

[BUGFIX] Fix new record controller xClass example

---

Configuration/TCA/Overrides/be_users.php
Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php

TYPO3_MODE is not defined anymore

[BUGFIX] defined('TYPO3') or die();

---

Classes/Controller/AdminModuleController.php
Classes/Controller/ModuleController.php
Configuration/Backend/Modules.php
Configuration/Services.yaml
Resources/Private/Language/AdminModule/locallang_mod.xlf
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Templates/AdminModule/Index.html
Resources/Private/Templates/Module/Clipboard.html
Resources/Private/Templates/Module/Debug.html
Resources/Private/Templates/Module/FileReference.html
Resources/Private/Templates/Module/Flash.html
Resources/Private/Templates/Module/Links.html
Resources/Private/Templates/Module/Log.html
Resources/Private/Templates/Module/Password.html
Resources/Private/Templates/Module/Tree.html
ext_conf_template.txt

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96812-NoFrontendTypoScriptBasedTemplateOverridesInTheBackend.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96730-SimplifiedExtbackendModuleTemplateAPI.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96733-NewBackendModuleRegistrationAPI.html#module-dependent-configuration-options
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96733-RemovedSupportForModuleHandlingBasedOnTBE_MODULES.html

[FEATURE] use New backend module registration API

---

Configuration/TCA/Overrides/tt_content.php
Configuration/TSconfig/Page/ContentElementWizard.typoscript
Configuration/TypoScript/DataProcessors/Processors/SiteLanguageProcessor.typoscript
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/ContentElements/DataProcSiteLanguage.html

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96800-AddSiteLanguageProcessor.html
refs https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/12

[FEATURE] #96800 - Add SiteLanguageProcessor

---

Classes/LinkHandler/GitHubLinkHandler.php

Resolves: #78
Releases: main, 11.5, 10.4

Remove unused variable

---

Classes/Controller/ModuleController.php

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/131

[TASK] Use ContextualFeedbackSeverity for flash message severity

---

composer.json

See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html#replace-with-typo3-ter-vendorname

[TASK] Remove typo3-ter/examples replace in composer.json

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
composer.json

`composer req --dev ergebnis/composer-normalize`
Can be run with:
- `composer normalize` or
- `Build/Scripts/runTests.sh -s composerNormalize`
Also activated in the "tests" workflow.

[TASK] Normalize composer.json

---

Classes/Controller/AdminModuleController.php
Classes/Controller/ErrorController.php
Classes/LinkHandler/GitHubLinkHandler.php
Classes/Userfuncs/Tca.php
ext_localconf.php
ext_tables.php

[TASK] Fix CGL issues after update of php-cs-fixer

---

CHANGELOG.md
Classes/EventListener/Core/Configuration/FlexFormParsingModifyEventListener.php
Configuration/Services.yaml

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/159
resolves https://github.com/TYPO3-Documentation/t3docs-examples/issues/116

[FEATURE] Events Listener for flex form parsing

---

.editorconfig
CHANGELOG.md
Classes/Command/DoSomethingCommand.php
Configuration/Services.yaml

This is a basic console command as it would be created by "Make"
resolves #119

[FEATURE] Create a basic console command example

---

Documentation/Includes.rst.txt
Documentation/Maintainers/CodeQuality/Index.rst
Documentation/Maintainers/Index.rst
composer.json

Additionally, add missing files to "prepare-release" script.

[TASK] Add check and fix commands as composer scripts

---

Configuration/TCA/tx_examples_dummy.php
Configuration/TCA/tx_examples_haiku.php
ext_tables.php

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/208

[TASK] Use ignorePageTypeRestriction instead EMU::allowTableOnStandardPages

---

CHANGELOG.md
Classes/Userfuncs/Tca.php

[BUGFIX] Fix TCA userfunc PHP warnings when no record is created yet

---

CHANGELOG.md
Classes/Controller/ModuleController.php
Classes/Service/TableInformationService.php
Configuration/Backend/Modules.php
Resources/Private/Templates/Module/Flash.html

In the doing: Move the querying of the database to a Service, this does not belong in a controller
resolves #83
releases: main

[BUGFIX] Fix the count-buttons in FlashMessage example for v12

---

Resources/Public/JavaScript/ContextMenuActions.js

references https://github.com/TYPO3-Documentation/t3docs-examples/issues/101

Fix comments in Context Menu example (v11)

---

Configuration/Flexforms/HtmlParser.xml
Configuration/Flexforms/PluginHaikuDetail.xml
Configuration/Flexforms/PluginHaikuList.xml
Configuration/Flexforms/flexform_ds1.xml
Configuration/Flexforms/flexform_ds2.xml
Configuration/Flexforms/flexform_ds3.xml
Configuration/Flexforms/flexform_ds4.xml

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/190

Remove "TCEforms" wrapper in FlexForm definitions

---

Classes/Controller/ModuleController.php
Resources/Private/Language/locallang.xlf

planning to use this as an extended example in TYPO3 Explained, Localization via PHP (Extbase)

[FEATURE] Let countAction return localized flash message

---

.gitattributes
.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
CHANGELOG.md
Classes/ContextMenu/HelloWorldItemProvider.php
Classes/Middleware/HaikuSeasonList.php
Classes/Userfuncs/Tca.php
Configuration/RequestMiddlewares.php
composer.json
rector.php

For now just one rule is applied: TernaryToNullCoalescingRector

[TASK] Introduce Rector

---

Classes/Controller/Haiku/ListController.php

Set class to final as (opinionated) best practise and properties to private as they are not needed outside the class (which would be bad practise anyway).

[TASK] Streamline Haiku ListController

---

CHANGELOG.md
Configuration/TypoScript/DataProcessors/Processors/CommaSeparatedValueProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/DatabaseQueryProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/FilesProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/GalleryProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/LanguageMenuProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/MenuProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/SiteLanguageProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/SiteProcessor.typoscript
Configuration/TypoScript/DataProcessors/Processors/SplitProcessor.typoscript

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/230

[FEATURE] Use alias for data processors provided by TYPO3 Core

---

Configuration/Services.yaml
Configuration/TypoScript/DataProcessors/Processors/CustomCategoryProcessor.typoscript

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/230

[FEATURE] Use alias for CustomCategoryProcessor

---

Classes/LinkHandler/GitHubLinkHandler.php
Configuration/Services.yaml

Apply changes @brotkrueml found during review in CoreApi
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2385

[BUGFIX] Apply changes to custom link handler

---

Classes/Controller/ModuleController.php

With this it's more clear how to create multiple file references.
Resolves: #

[TASK] Create multiple file references

---

Classes/Controller/AdminModuleController.php
Configuration/Services.yaml

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/272

[TASK] Use backend controller attribute

---

ext_emconf.php

Add required extensions to ext_emconf.php

---

Classes/ContextMenu/HelloWorldItemProvider.php

This is a PR to fix CI pipeline, which affected PR #177 but is unrelated to the change, see https://github.com/TYPO3-Documentation/t3docs-examples/actions/runs/4666637727/jobs/8261448447?pr=177

[TASK] CGL fix

---

Classes/EventListener/Core/Configuration/FlexFormParsingModifyEventListener.php

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/570

[TASK] Remove superfluous "TCEforms" key from FlexForms

---

Configuration/TCA/Overrides/pages.php

It is already added in Configuration/TSconfig/User

[TASK] Remove duplicate tsconfig

---

composer.json
ext_emconf.php

It is now in a separate branch

!!![TASK] Drop support for TYPO3 v12

---

.github/workflows/backport.yml

[CI] Add backport workflow

---

composer.json

[TASK] Update dev dependencies

---

composer.json

[BUGFIX] Correct branch alias

---

ext_emconf.php

[TASK] Adjust TYPO3 version constraints

---

.github/workflows/tests.yml

[CI] Add PHP 8.3 to workflow matrix

---

Resources/Private/Language/AdminModule/locallang_mod.xlf
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Language/PluginHaiku/de.locallang.xlf
Resources/Private/Language/PluginHaiku/locallang.xlf
Resources/Private/Language/PluginHaiku/locallang_db.xlf
Resources/Private/Language/custom.xlf
Resources/Private/Language/de.custom.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_browse_links.xlf
Resources/Private/Language/locallang_db.xlf

- Remove superfluous "xmlns:t3" namespace
- Set "original" attribute to file name
- Collapse empty "header" tag

[TASK] Streamline XLIFF files

---

CHANGELOG.md

[DOCS] Add v12 releases to changelog

---

CHANGELOG.md
Classes/Controller/ModuleController.php

[BUGFIX] Avoid dynamic properties in ModuleController

---

CHANGELOG.md
Classes/Controller/AdminModuleController.php

[BUGFIX] Use correct object to call pushModuleData() method in AdminModuleController (#225)

---

Classes/Controller/AdminModuleController.php

- Switch from Controller attribute to AsController attribute
- Fix language labels for titles and options
- Switch value for setShowLabelText() to a valid boolean

Update AdminModuleController.php (Backend Module w/o Extbase)

---

CHANGELOG.md

[DOCS] Add changelog for version 12.0.3

---

CHANGELOG.md

[DOCS] Add changelog for v12.0.4

---

CHANGELOG.md

[TASK] Add release date to version 12.0.5 in changelog

---

composer.json

[TASK] Allow Usage with TYPO3 13.1

---

Build/phpstan/phpstan.neon
Classes/Controller/ModuleController.php

Fix error in module controller, there is no findall method in the file repository.

[TASK] Raise phpstan level to 2

---

Build/phpstan/phpstan.neon
Classes/Controller/HtmlParserController.php

[TASK] Raise PHPstan level to 5

---

Build/phpstan/phpstan.neon
Classes/ContextMenu/HelloWorldItemProvider.php
Classes/DataProcessing/CustomCategoryProcessor.php

[TASK] Raise PHPstan level to 7

---

Build/phpstan/phpstan.neon
Classes/Controller/ModuleController.php

[TASK] Raise PHPstan level to 8

---

Classes/Controller/AdminModuleController.php

Depends on #271
resolves https://github.com/TYPO3-Documentation/t3docs-examples/issues/110

[BUGFIX] Fix link in Admin Module

---

Classes/Controller/ModuleController.php
Resources/Private/Partials/Module/CreateHaikuBlankLink.html
Resources/Private/Partials/Module/CreateHaikuLink.html
Resources/Private/Partials/Module/EditPage1Link.html
Resources/Private/Partials/Module/EditPage2Link.html
Resources/Private/Templates/Module/Links.html

Move link examples to Partials so they can be included individually

[TASK] Update and Improve Backend UriBuilder examples

---

Configuration/TCA/tx_examples_dummy.php
Configuration/TCA/tx_examples_haiku.php

References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/967
Releases: main

[FEATURE] Add default TCA columns from ctrl

---

.github/workflows/tests.yml
Classes/Controller/ModuleController.php

It currently throws errors and makes the tests red without reason.
Releases: 12.4

[BUGFIX] Remove rector for version 12.4

---

.github/workflows/tests.yml
Build/rector/rector.php
Configuration/TCA/Overrides/tt_content.php
Makefile

Exclude rector from tests on action
Releases: main

[BUGFIX] Run Rector and fix CGL

---

ext_emconf.php

This also prevents TYPO3 Exception 1303237468 https://github.com/TYPO3-Documentation/t3docs-examples/pull/287

[BUGFIX] Align requirements for Composer and legacy installs

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh

[CI] Lint code with PHP 8.4

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh

[CI] [Backport 12.4] Lint code with PHP 8.4 (#295)

---

.gitignore
Build/Scripts/runTests.sh
Build/rector/composer.json
Classes/Upgrades/ExtbasePluginListTypeToCTypeUpdate.php
Classes/Upgrades/HaikuPluginListTypeToCTypeUpdate.php
Makefile
composer.json

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1071
Releases: main

[TASK] Add list_type to CType Upgrade Wizards

---

Configuration/Sets/Examples/settings.definitions.yaml

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1083
Releases: main

[TASK] Add site setting with enum

---

composer.json

[TASK] Allow TYPO3 13.4
