TYPO3-Documentation/t3docs-examples

Classes/Controller/ModuleController.php
README.rst
ext_localconf.php
ext_tables.sql

Updated examples for the Logging Framework to use LoggerAwareInterface instead of GeneralUtility::makeInstance.
Added a working example to write the log to a custom database table.

Updated examples for the Logging Framework

---

.github/workflows/publish.yml
composer.json

Publish new releases automatically to the TYPO3 Extensions Repository along with the already-in-place deployments to Packagist and the TYPO3 documentation.
Fixes: #37

[TASK] Publish TER release by GitHub Action

---

Documentation/Settings.cfg

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185

[DOCS] Reference manual's start page with :doc:`<manual>:Index`

---

Classes/Controller/ModuleController.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Module/Links.html

In the backend module "Example module" in the function "Links",
there are several links to edit records. After the "close"
button is clicked in the form, the expected behaviour would be,
to jump back to the previously opened module.
This functionality can be implemented, by setting returnUrl to
the module route. This is now implemented in one of the links
and an appropriate label added.
Resolves: #84

[FEATURE] Add returnUrl in module "Links"

---

composer.json

Also, it is recommended to separate different versions with || instead of |.
See: https://getcomposer.org/doc/articles/versions.md#version-range
Additionally, allow plugins - which is necessary since composer 2.2, so
composer plugins are executed in this project.

[TASK] Add missing constraints in composer.json

---

Classes/DataProcessing/CustomCategoryProcessor.php
Classes/Domain/Model/Category.php
Classes/Domain/Repository/CategoryRepository.php
Configuration/Extbase/Persistence/Classes.php

The CategoryRepository shipped with Extbase was removed in TYPO3 v12.
In addition, we have also to provide the model.

[BUGFIX] Use custom CategoryRepository

---

.gitattributes

This avoids installing dot-files (development files) when running
"composer require" with a stable version.

[TASK] Introduce .gitattributes

---

.gitignore
composer.json

This makes the project's root folder less cluttered when executing
"composer update".
vendor -> .Build/vendor
vendor/bin -> .Build/bin
public -> .Build/web
This is in line with the bootstrap_package and styleguide extensions.
Additionally, ignore the .Build folder and a composer.lock file.

[TASK] Store installation artifacts in .Build folder

---

CHANGELOG.md

The format is better readable and is somehow standardized.
Also added the changes since start of 12.0 development. The very old
changes were discarded, mostly they can't assigned to a version anymore
("Release of version 0.7.0" is listed twice in separate sections, with
0.6 between).
See also:
- https://keepachangelog.com/
- https://github.com/TYPO3-Documentation/tea/blob/main/CHANGELOG.md

[TASK] Move changelog to "Keep a Changelog"

---

Configuration/Backend/Modules.php

This avoids the missing image icon displayed for backend
modules. We use the "module-generic" icon identifier provided
by TYPO3.

[BUGFIX] Add missing icons to backend modules

---

Configuration/Backend/Modules.php
Configuration/Icons.php
ext_tables.php

A left-over from the migration to Configuration/Backend/Modules.php
is ext_tables.php is removed.
This way, I encountered also that there is already a backend module
icon in this extension, which is now registered and used for the two
backend modules.

[TASK] Clean up module registration

---

Classes/ContextMenu/HelloWorldItemProvider.php
ext_localconf.php

This is not necessary anymore, as every class implementing
`TYPO3\CMS\Backend\ContextMenu\ItemProviders\ProviderInterface`
is registered automatically.
Additionally, the context menu icon was changed to differ
from the info context menu with the same icon directly above.

[TASK] Remove superfluous context menu item provider registration

---

Configuration/TCA/tx_examples_dummy.php
Configuration/TCA/tx_examples_haiku.php

Additionally, cruser_id was also removed. dividers2tabs was removed some versions ago
and has no influence in modern versions.
In dummy table a description field was configured but not displayed, this was also
corrected.

[TASK] Use new TCA types

---

ext_localconf.php

Target is to replace the xclass by another one.  
The previous example can't be updated without much hacks--if at all.

disable xclass, see #60

---

Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php

The `addStaticFile` call on `Configuration/TypoScript/`
is called in `tt_content.php` and `sys_template.php`.
Therefore, one is removed.

[BUGFIX] Remove duplicate adding of TypoScript

---

Classes/Command/CatFactCommand.php
Classes/Command/MeowInformationCommand.php
Classes/Http/CatFactRequester.php
Classes/Http/MeowInformationRequester.php
Configuration/Services.yaml

This example will be used as code snippet for
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Http/Index.html#basic-usage
The main part is the MeowInformationRequester class which requests a cat information
from a public API. To hold the example small only the needed code is
available in this class. To really work with the MeowInformationRequester a
MeowInformationCommand is introduced which can be called with
`vendor/bin/typo3 examples:meow` and displays a random information piece
about cats.
Resolves: #108

[FEATURE] Add example for sending HTTP request with Guzzle

---

Classes/EventListener/Core/Configuration/FlexFormParsingModifyEventListener.php

As it was always executed, messing up the other examples

[BUGFIX] Fix the FlexFormParsingModifyEventListener

---

Classes/Controller/Haiku/DetailController.php
Classes/Controller/Haiku/ListController.php
Classes/Service/StandaloneViewService.php

Since the StandaloneView does not create an Extbase request anymore, calling the Haiku list plugin throws the following warning:
ViewHelper f:link.page needs a request implementing ServerRequestInterface.
This is fixed by setting the current request object into the StandaloneView from the plugin.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/197

[BUGFIX] Inject Request object into StandaloneView

---

composer.json

This avoids an error on a TYPO3 installation without installed linkvalidator on DI compile time:
Cannot autowire service "T3docs\Examples\EventListener\LinkValidator\CheckExternalLinksToLocalPagesEventListener": argument "$brokenLinkRepository" of method "__construct()" has type "TYPO3\CMS\Linkvalidator\Repository\BrokenLinkRepository" but this class was not found.
Additionally, allow composer plugins.

[BUGFIX] Require linkvalidator in v11-compatible version

---

CHANGELOG.md
Classes/LinkHandler/GitHubLinkHandler.php
Classes/LinkHandler/GithubLinkBuilder.php
Configuration/TsConfig/Page/Extension/Linkhandler.tsconfig
ext_localconf.php

Forward port from https://github.com/TYPO3-Documentation/t3docs-examples/pull/132
The TypolinkBuilder was missing all together. This example can never have worked as in promised in the docs
releases: main

[Forwardport] [BUGFIX] Correct GitHub Linkhandler

---

Configuration/TsConfig/Page/Extension/Linkhandler.tsconfig
Configuration/TsConfig/Page/LinkBrowser/HaikuRecordLinkBrowser.tsconfig
Configuration/TypoScript/PluginHaiku/constants.typoscript
Configuration/TypoScript/RecordLinks/Haiku.typoscript
Configuration/page.tsconfig

Isolate the record link TSconfig to its own file as it is easier to display and link to in the documentation. Move the TSconfig from "Extension" as the link browser is part of typo3/cms-backend and an integral part of the TYPO3 Core.
Adjust the TypoScript so the Haiku Detail view links to the detail view of our non-Extbase Plugin example.
On the fly: Add comment-editor comments to the Haiku Plugin constants.
The custom github linkhandler TSconfig will be moved in a follow-up

[FEATURE] Improve the record link browser example

---

.editorconfig
.github/workflows/tests.yml

We currently only need to run the linting on the supported PHP versions.
Checking the normalization of composer.json file or if the code styles 
are applied well can be done in one PHP version only. 
This saves resources and keeps the workflow slim.

[CI] Split up workflows

---

Resources/Private/Language/AdminModule/locallang_mod.xlf
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Language/PluginHaiku/de.locallang.xlf
Resources/Private/Language/PluginHaiku/locallang.xlf
Resources/Private/Language/PluginHaiku/locallang_db.xlf
Resources/Private/Language/custom.xlf
Resources/Private/Language/de.custom.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_browse_links.xlf
Resources/Private/Language/locallang_db.xlf

This was done with [t3ll](https://github.com/garfieldius/t3ll). Additionally, the keys are sorted alphabetically.
XLIFF version 1.2 can be validated against a schema. Next step would then be to lint the XLIFF files in a CI run.

[TASK] Convert XLIFF files to version 1.2

---

ATTRIBUTION.txt
LICENSE.txt

As this repository is under the GPL v2 license (as stated in the composer.json file) we should deliver this file also to users.
The previous attribution text was moved to a new ATTRIBUTION.txt file.

[TASK] Use GPL v2 in LICENSE.txt file

---

Classes/Controller/Haiku/DetailController.php

With PHP 8.1 a new return type "never" was introduced. This type declares that the method would - well - never return anything. So we add it to notFoundAction(). Then we can streamline the main() method to return immediately instead of assigning the result to a variable and return later.
This is a preparation for applying more Rector rules.
Additionally, set class to final as opinionated best practise and properties to private as they are not needed outside (which would be bad practise anyway).

[TASK] Streamline Haiku DetailController

---

Classes/Command/MeowInformationCommand.php
Classes/Http/MeowInformationRequester.php
rector.php

We do not need to throw an exception ourselves then as json_decode will throw an error now when parsing the json failed

[BUGFIX] Use flag JSON_THROW_ON_ERROR

---

Classes/Controller/AdminModuleController.php
Classes/LinkHandler/GithubLinkBuilder.php
rector.php

This is the first part of applying the UP_TO_PHP_xx level set lists until PHP 8.1. This way the changes are small.
The TernaryToNullCoalescingRector is part of the PHP 7.0 rule set and can therefore be omitted.
The GithubLinkBuilder::TYPE_GITHUB constant was set to private manually as the Rector rule would set it to public (which is not needed in this case).
The moduleTemplateFactory->create() method only accepts one argument, therefore Rector removed the second one.
The AddLiteralSeparatorToNumberRector is skipped as this would format exception codes (timestamps) like 1_234_567_890 (which is not needed for readability here).

[TASK] Apply UP_TO_PHP_74 level set list to Rector rules

---

Classes/Controller/ModuleController.php

This happens when selecting the "Clipboard" third-level module:
PHP Warning: Undefined array key "tx_examples_tools_examplesexamples" in Classes/Controller/ModuleController.php line 222

[BUGFIX] Avoid undefined array key in clipboard module

---

composer.json

In order to unify some paths across extension, it is recommended to use web-dir ".Build/Web".
For examples, this does not have any impact, as the web-dir is currently not used.
But, in general, the paths are sometimes used in scripts (runTests.sh) or configuration files (e.g. phpstan.neon), so it helps to unify things if the common defaults are used.
This concerns:
- web-dir: .Build/Web
- bin-dir: .Build/bin
- vendor-dir: .Build/vendor
Related: TYPO3-Documentation/tea#802

[TASK] Unify web-dir in composer.json

---

Resources/Private/Templates/ContentElements/DataProcMenu.html

* Use data-bs-toggle instead of data-toggle
* Remove aria-expanded. It is not used in the bootstrap examples anymore
* Remove a white space
* Use hasSubpages instead of counting the children
* Add missing data to access the page UID of subpages

Adopt menu processor example to Bootstrap 5

---

Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/tt_content.php

This avoids deprecation notices and TCA migrations.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/401

[TASK] Use associative array keys for TCA items

---

Configuration/TCA/tx_examples_haiku.php

The overrideChildTCA does not matter in this case and is omitted:
- image overlay palette is the default
- a text file type is not possible with image fields
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-98479-DeprecatedFileReferenceRelatedFunctionality.html

[TASK] Substitute ExtensionManagementUtility::getFileFieldTCAConfig() with TCA file type

---

ext_localconf.php
ext_tables.php

I just had a talk with lolli,`ExtensionManagementUtility::addUserTSConfig` may only be called int the ext_localconf.php, see also the comment for that method.

[BUGFIX] Move ExtensionManagementUtility::addUserTSConfig

---

ext_localconf.php
ext_tables.php

I just had a talk with lolli,`ExtensionManagementUtility::addUserTSConfig` may only be called int the ext_localconf.php, see also the comment for that method.

[BUGFIX] Move ExtensionManagementUtility::addUserTSConfig (#193)

---

composer.json

This way, PhpStorm picks up this version as language level.

[TASK] Explicitly define PHP version constraint

---

composer.json

This way, PhpStorm picks up this version as language level.

[Backport 12.4] [TASK] Explicitly define PHP version constraint (#197)

---

Classes/LinkValidator/LinkType/ExampleLinkType.php

TYPO3 v13 complains about missing return types in overwritten methods. These are now added.
Also, `getLL()` has been deprecated in v12 and removed in v13.
Releases: main

[BUGFIX] Adjust ExampleLinkType for v13

---

Classes/ContextMenu/HelloWorldItemProvider.php
Classes/Controller/Haiku/DetailController.php
Classes/Http/MeowInformationRequester.php
Classes/LinkHandler/GitHubLinkHandler.php
Configuration/TCA/Overrides/tt_content_plugin_haiku_detail.php
Configuration/TCA/Overrides/tt_content_plugin_haiku_list.php

[TASK] Fix CGL after update of php-cs-fixer to v3.23.0

---

.github/workflows/publish.yml
.github/workflows/tests.yml

This also avoid the following deprecation on publish: "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2."
Additionally, use ubuntu-latest instead of a dedicated version to avoid outdated Ubuntu versions which are not supported anymore by GitHub in the future.

[CI] Update actions/checkout to version 4

---

CHANGELOG.md
Classes/Controller/ModuleController.php

[Backport 12.4] [BUGFIX] Avoid dynamic properties in ModuleController (#224)

---

CHANGELOG.md
Classes/Controller/AdminModuleController.php

[BUGFIX] Use correct object to call pushModuleData() method in AdminModuleController

---

Configuration/Backend/Modules.php

As there is no need to set the extensionName option according to TYPO3 API Docs.

Fix module registration for plain (non-extbase) controller

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
composer.json

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/781
Releases: main

[CI] Run tests on at least PHP 8.2

---

.php-cs-fixer.dist.php
Configuration/Backend/Modules.php
composer.json

typo3/coding-standards is not compatible with Symfony 7 (necessary for TYPO3 v13), so we use php-cs-fixer directly instead of relying on another package.
The rules for the php-cs-fixer are the same as for TYPO3 Core.

[TASK] Use php-cs-fixer

---

CHANGELOG.md
Classes/Controller/ModuleController.php

This is necessary to be compatible with TYPO3 v13.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/810
Releases: main

[TASK] Add return type to ModuleController->initializeAction()

---

CHANGELOG.md
Classes/Command/DoSomethingCommand.php
Classes/Command/MeowInformationCommand.php
Configuration/Services.yaml

The CreateWizardCommand can't be adjusted to use the attribute as it is set to `schedulable: false` (which is not possible with the Symfony attribute).
Additionally, the DoSomethingCommand is defined as final.
Releases: main

[TASK] Use attribute in commands

---

Classes/Controller/AdminModuleController.php
Classes/EventListener/LinkValidator/CheckExternalLinksToLocalPagesEventListener.php
Classes/Http/MeowInformationRequester.php
Classes/Middleware/HaikuSeasonList.php
rector.php

[TASK] Set PHP level to 8.2 via Rector

---

Classes/Command/DoSomethingCommand.php
Configuration/Services.yaml

In TYPO3 Explained we use this snipped in the commands tutorial. We'll describe there the tagging of commands via Services.yaml as the property `schedulable` (which is described there) is not available via the attribute.
Releases: main

[TASK] Restore tagging via Services.yaml for DoSomethingCommand

---

Configuration/Flexforms/HtmlParser.xml
Configuration/Flexforms/PluginHaikuDetail.xml
Configuration/Flexforms/PluginHaikuList.xml
Configuration/Flexforms/flexform_ds1.xml
Configuration/Flexforms/flexform_ds2.xml
Configuration/Flexforms/flexform_ds3.xml
Configuration/Flexforms/flexform_ds4.xml

This is deprecated since 7.6
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/7.6/Deprecation-70138-FlexFormLanguageHandling.html#description

[TASK] Remove outdated langDisable and langChildren tags

---

CHANGELOG.md
composer.json
ext_emconf.php

When running the command
vendor/bin/typo3 setup:extension -e examples
the following warning was raised:
[WARNING] examples contains data to be imported, but the required component is not installed. Make sure  to define
corresponding requirements.
This change adds EXT:impexp as dependency requirement.
Resolves: #253

[BUGFIX] Avoid warning when set up extension

---

CHANGELOG.md
composer.json
ext_emconf.php

When running the command
vendor/bin/typo3 setup:extension -e examples
the following warning was raised:
[WARNING] examples contains data to be imported, but the required component is not installed. Make sure  to define
corresponding requirements.
This change adds EXT:impexp as dependency requirement.
Resolves: #253

[BUGFIX] Avoid warning when set up extension (#256)

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/phpstan/phpstan-baseline.neon
Build/phpstan/phpstan-typo3-constants.php
Build/phpstan/phpstan.neon
Classes/Controller/ModuleController.php
Classes/DataProcessing/CustomCategoryProcessor.php
Classes/Xclass/NewRecordController.php
composer.json

The TYPO3 Core and the Best Practice Team recommends
to have a static code analyzer in the defense line,
and preferes PHPStan due to experience with that tool.
This change now adds the static code analyser `PHPStan`
with a first configurattion and a lower level as a start.
Levels can be raised step by step in follow-ups.
Note: XClass `Classes/Xclass/NewRecordController.php`
example does not work anymore, most likely since v12.
Added a comment to emphasize this, and that it should
be reworked or removed.
PHPStan can be run with
```terminal
Build/Scripts/runTests.sh -s phpstan
```
Generate baseline with
```terminal
Build/Scripts/runTests.sh -s phpstanBaseline
```
> Depends on #261

[TASK] Add static code analyser `PHPStan` as code quality check

---

Classes/Form/Element/SpecialFieldElement.php

$parameterArray['fieldChangeFunc'] is passed as
UpdateValueOnFieldChange and not a string anymore.
This causes type errors when you try to create a new FE user
Releases: main

[BUGFIX] Fix creating a special field

---

Classes/Controller/AdminModuleController.php
Classes/Controller/ModuleController.php

Related https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4435

[BUGFIX] Do not reuse DataHandler

---

Configuration/Sets/Examples/settings.definitions.yaml
Documentation/Introduction/Index.rst

This showcases how the actual site set settings definition set of settings can be set in the documentation of auto-generated settable site set settings.

[TASK] Add exemplary site set settings definition

---

Classes/Controller/AdminModuleController.php
Classes/Controller/ModuleController.php

As the class is defined as final, it does not make sense to set the properties as protected as this class cannot be extended.

[TASK] Mark properties as private in AdminModuleController (#283)

---

Configuration/Sets/Examples/settings.definitions.yaml

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1026
Releases: main

[FEATURE] Demonstrate all possible site setting types

---

Resources/Private/Language/AdminModule/locallang_mod.xlf
Resources/Private/Language/Module/locallang.xlf
Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Language/PluginHaiku/de.locallang.xlf
Resources/Private/Language/PluginHaiku/locallang.xlf
Resources/Private/Language/PluginHaiku/locallang_db.xlf
Resources/Private/Language/custom.xlf
Resources/Private/Language/de.custom.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_browse_links.xlf
Resources/Private/Language/locallang_db.xlf

References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1167
Releases: main

[TASK] Get rid of "resname" attribute in XLF files

---

Configuration/TsConfig/Page/LinkBrowser/HaikuRecordLinkBrowser.tsconfig

The class `TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler` was removed in https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98443-ExtensionRecordlistMergedIntoBackend.html in TYPO3 12.0
TYPO3 12 still worked with the old handler setting, because there was an alias/fallback defined: https://github.com/TYPO3/typo3/blob/b4c9dea13902b0350263d70f189f622ee940eb71/typo3/sysext/backend/Configuration/Services.yaml#L126
The alias was removed in TYPO3 13 and the example in the documentation does not work anymore. 
This commit should be also backported to the `13.4` branch. Maybe even to `12.4`?

[BUGFIX] Update namespace of RecordLinkHandler

---

ext_emconf.php

This category causes the extension to appear in the Extension Manager for Classic installations when extensions are being loaded.
See https://forge.typo3.org/issues/106701

Remove "Distribution" category
